### ISSUE TITLE
【BUG】启动Nonebot的时候报错

### ISSUE THREAD

**Issue by RonenWen** [MoRan23/GZCTF-BOT-QQ#3]
错误信息：11-03 13:52:44 [ERROR] apscheduler | Job "_ (trigger: interval[0:00:20], next run at: 2024-11-03 21:53:04 CST)" raised an exception
Traceback (most recent call last):
  File "/root/GZCTF-BOT-QQ/bot.py", line 17, in <module>
    nonebot.run()
  File "/usr/local/lib/python3.10/site-packages/nonebot/__init__.py", line 335, in run
    get_driver().run(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 186, in run
    uvicorn.run(
  File "/usr/local/lib/python3.10/site-packages/uvicorn/main.py", line 579, in run
    server.run()
  File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
> File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
  File "/root/GZCTF-BOT-QQ/gzctf-bot/plugins/gzctf_bot_qq/main_bot.py", line 1326, in _
    bot = get_bot()
  File "/usr/local/lib/python3.10/site-packages/nonebot/__init__.py", line 230, in get_bot
    raise ValueError("There are no bots to get.")
ValueError: There are no bots to get.

配置过程：
参考https://github.com/MoRan23/GZCTF-BOT-QQ进行的配置，使用docker-compose进行部署
成功登录了qq，但是Nonebot

**Comment by MoRan23** [comment]
配置不对，在检查检查或者给个截图看看

**Comment by MoRan23** [comment]
你给的报错是没连上qq

**Comment by RonenWen** [comment]
![image](https://github.com/user-attachments/assets/2a1d38b8-c573-42ee-b22a-ec78b6eb063f)
napcat的镜像我死活拉不下来，所以是用海外机器拉的，push到我自己的阿里云仓库
![image](https://github.com/user-attachments/assets/f7abe6cd-ff61-45e6-9f63-1bc40a89000f)
登录似乎是成功了，能收到信息

bot的报错信息依然存在
![image](https://github.com/user-attachments/assets/413ba81c-9015-40ca-907c-1c8077777644)

**Comment by MoRan23** [comment]
？哥，
![image](https://github.com/user-attachments/assets/f2995bcf-30c5-4786-9bfa-bb185dda5096)

**Comment by MoRan23** [comment]
都成功了哥
错误日志是不会自己删的哥

**Comment by RonenWen** [comment]
好吧。。。刚刚一直在弹那个报错。
有什么指令能够测试机器人部署成功了么？

**Comment by MoRan23** [comment]
私聊发个/help

**Comment by RonenWen** [comment]
感谢
